server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ecommerce?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql:

api:
  prefix: /api/v1

jwt:
  secret: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  expiration: 900            # access token (15 phút)
  refresh-expiration: 2592000 # refresh token (30 ngày)

logging:
  level:
    org.springframework.security: DEBUG

